### PR TITLE
Allow usage of accounts not defined in config

### PR DESCRIPTION
**Pull request by christianmkuss**
Currently the only way to use the functions are to use the server key from
the config file. For instances when another account not used in the config
is required you can pass an optional server_key to all functions except
test token (because it is only for testing).

### CODE REVIEW

**Comment by rizdaprasetya** [comment]
Hi @christianmkuss thanks for the concern and PR, but I think that might not be the best way to handle multi account/server-key by introducing new parameter.

There's better way in current implementation:
https://github.com/veritrans/veritrans-ruby/blob/826cef033dd570be31c2b735ee7928b76917d7a0/lib/veritrans.rb#L54-L66

It might not properly documented on Readme, but yes it's possible to use multi account/server-key.
we'll consider to put it on Readme for better visibility.

Let us know if you think there's issue with that current method of handling multi account/server-key.

Thanks

**Comment by christianmkuss** [comment]
Thanks for the feedback. I am new to Ruby but it sort of feels like overkill to create an object when the only thing that needs to change between profiles (using only charge and the general api requests) is the server key.

I was also confused by the use of the optional parameter `auth_header` in the `make_request` function. Every usage I could find never passed a parameter for `auth_header` therefore it was always nil.

**Comment by rizdaprasetya** [comment]
Yes, I got your concern. But the library is following Object Oriented pattern. Within OO world It's not overkill to create an instance of object based on different properties. Additionally now you'll have 2 instance of it let's say:
- midtrans_client_A
- midtrans_client_B

Which you can conveniently refer within your code, incase you want to know which one need to call API. Without explicitly passing server_key on each API call.

My concern about adding more param to each function call might hurt overall maintainability of the repo.

But let's see what @Paxa  opinion on this, once he have time to check the PR.

Regarding `auth_header` param, yes it seems unused, maybe the original dev switched to read from the object prop / config instead while along the development process.

**Comment by Paxa** [comment]
I can be useful in some cases, let me think and review code later
btw what you think about named arguments e.g. `server_key: nil` so we can add more arguments later easily

**Comment by Andrenzo17** [comment]
Hi @christianmkuss thanks for the open PR.

Currently in our library, if you want use multi account you can create instance like example below

```
mt_test = Midtrans.new(
      server_key: "SB-Mid-server-uQmMImQMeo0Ky3Svl90QTUj2",
      client_key: "SB-Mid-client-ArNfhrh7st9bQKmz",
      api_host: "https://api.sandbox.midtrans.com",
      logger: Logger.new(STDOUT),
      file_logger: Logger.new(STDOUT)
    )
```
    
```
mt_test_invalid_key = Veritrans.new(
      server_key: "invalid server key",
      client_key: "invalid client key",
      api_host: "https://api.sandbox.midtrans.com",
      logger: Logger.new(STDOUT),
      file_logger: Logger.new(STDOUT)
 )
```
 Here is the example of usage multi account https://github.com/veritrans/veritrans-ruby/blob/master/lib/test/snap_test.rb
 
More detail about Client Initialization and Configuration https://github.com/veritrans/veritrans-ruby#22-client-initialization-and-configuration

Thank you

**Pull request closed without merging**
